/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustSystemRouteImport } from './routes/trust-system'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as SpacesLocationRouteImport } from './routes/spaces.$location'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedViewingsRouteImport } from './routes/_authenticated/viewings'
import { Route as AuthenticatedVerificationHubRouteImport } from './routes/_authenticated/verification-hub'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedTrustRouteImport } from './routes/_authenticated/trust'
import { Route as AuthenticatedSafetyRouteImport } from './routes/_authenticated/safety'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedBusinessIntelligenceRouteImport } from './routes/_authenticated/business-intelligence'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPropertyIdRouteImport } from './routes/_authenticated/property.$id'
import { Route as AuthenticatedDashboardSearchesRouteImport } from './routes/_authenticated/dashboard.searches'
import { Route as AuthenticatedDashboardPropertiesRouteImport } from './routes/_authenticated/dashboard.properties'
import { Route as AuthenticatedDashboardPerformanceRouteImport } from './routes/_authenticated/dashboard.performance'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard.favorites'
import { Route as AuthenticatedDashboardAgentPerformanceRouteImport } from './routes/_authenticated/dashboard.agent-performance'
import { Route as AuthenticatedDashboardSectionRouteImport } from './routes/_authenticated/dashboard.$section'
import { Route as AuthenticatedBillingHistoryRouteImport } from './routes/_authenticated/billing.history'
import { Route as AuthenticatedAdminSectionRouteImport } from './routes/_authenticated/admin.$section'
import { Route as ApiPublicOgPropertyIdRouteImport } from './routes/api/public/og.property.$id'
import { Route as AuthenticatedDashboardPropertiesIdManageRouteImport } from './routes/_authenticated/dashboard.properties.$id.manage'

const TrustSystemRoute = TrustSystemRouteImport.update({
  id: '/trust-system',
  path: '/trust-system',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesLocationRoute = SpacesLocationRouteImport.update({
  id: '/spaces/$location',
  path: '/spaces/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViewingsRoute = AuthenticatedViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationHubRoute =
  AuthenticatedVerificationHubRouteImport.update({
    id: '/verification-hub',
    path: '/verification-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustRoute = AuthenticatedTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyRoute = AuthenticatedSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessIntelligenceRoute =
  AuthenticatedBusinessIntelligenceRouteImport.update({
    id: '/business-intelligence',
    path: '/business-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPropertyIdRoute = AuthenticatedPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardSearchesRoute =
  AuthenticatedDashboardSearchesRouteImport.update({
    id: '/searches',
    path: '/searches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPropertiesRoute =
  AuthenticatedDashboardPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerformanceRoute =
  AuthenticatedDashboardPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentPerformanceRoute =
  AuthenticatedDashboardAgentPerformanceRouteImport.update({
    id: '/agent-performance',
    path: '/agent-performance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSectionRoute =
  AuthenticatedDashboardSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedBillingHistoryRoute =
  AuthenticatedBillingHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const AuthenticatedAdminSectionRoute =
  AuthenticatedAdminSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicOgPropertyIdRoute = ApiPublicOgPropertyIdRouteImport.update({
  id: '/api/public/og/property/$id',
  path: '/api/public/og/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardPropertiesIdManageRoute =
  AuthenticatedDashboardPropertiesIdManageRouteImport.update({
    id: '/$id/manage',
    path: '/$id/manage',
    getParentRoute: () => AuthenticatedDashboardPropertiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-system': typeof TrustSystemRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/deals': typeof AuthenticatedDealsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/verification-hub': typeof AuthenticatedVerificationHubRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/spaces/$location': typeof SpacesLocationRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/billing/history': typeof AuthenticatedBillingHistoryRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/dashboard/agent-performance': typeof AuthenticatedDashboardAgentPerformanceRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/properties': typeof AuthenticatedDashboardPropertiesRouteWithChildren
  '/dashboard/searches': typeof AuthenticatedDashboardSearchesRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/properties/$id/manage': typeof AuthenticatedDashboardPropertiesIdManageRoute
  '/api/public/og/property/$id': typeof ApiPublicOgPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-system': typeof TrustSystemRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/deals': typeof AuthenticatedDealsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/verification-hub': typeof AuthenticatedVerificationHubRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/spaces/$location': typeof SpacesLocationRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/billing/history': typeof AuthenticatedBillingHistoryRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/dashboard/agent-performance': typeof AuthenticatedDashboardAgentPerformanceRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/properties': typeof AuthenticatedDashboardPropertiesRouteWithChildren
  '/dashboard/searches': typeof AuthenticatedDashboardSearchesRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard/properties/$id/manage': typeof AuthenticatedDashboardPropertiesIdManageRoute
  '/api/public/og/property/$id': typeof ApiPublicOgPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-system': typeof TrustSystemRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRouteWithChildren
  '/_authenticated/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/safety': typeof AuthenticatedSafetyRoute
  '/_authenticated/trust': typeof AuthenticatedTrustRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/verification-hub': typeof AuthenticatedVerificationHubRoute
  '/_authenticated/viewings': typeof AuthenticatedViewingsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/spaces/$location': typeof SpacesLocationRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_authenticated/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/_authenticated/billing/history': typeof AuthenticatedBillingHistoryRoute
  '/_authenticated/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/_authenticated/dashboard/agent-performance': typeof AuthenticatedDashboardAgentPerformanceRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/_authenticated/dashboard/properties': typeof AuthenticatedDashboardPropertiesRouteWithChildren
  '/_authenticated/dashboard/searches': typeof AuthenticatedDashboardSearchesRoute
  '/_authenticated/property/$id': typeof AuthenticatedPropertyIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/properties/$id/manage': typeof AuthenticatedDashboardPropertiesIdManageRoute
  '/api/public/og/property/$id': typeof ApiPublicOgPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/contact'
    | '/design-system'
    | '/help'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-system'
    | '/admin'
    | '/billing'
    | '/business-intelligence'
    | '/compare'
    | '/dashboard'
    | '/deals'
    | '/leads'
    | '/messages'
    | '/notifications'
    | '/reviews'
    | '/safety'
    | '/trust'
    | '/upload'
    | '/verification'
    | '/verification-hub'
    | '/viewings'
    | '/welcome'
    | '/profile/$handle'
    | '/properties/$slug'
    | '/spaces/$location'
    | '/properties/'
    | '/admin/$section'
    | '/billing/history'
    | '/dashboard/$section'
    | '/dashboard/agent-performance'
    | '/dashboard/favorites'
    | '/dashboard/performance'
    | '/dashboard/properties'
    | '/dashboard/searches'
    | '/property/$id'
    | '/admin/'
    | '/dashboard/properties/$id/manage'
    | '/api/public/og/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/contact'
    | '/design-system'
    | '/help'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-system'
    | '/billing'
    | '/business-intelligence'
    | '/compare'
    | '/dashboard'
    | '/deals'
    | '/leads'
    | '/messages'
    | '/notifications'
    | '/reviews'
    | '/safety'
    | '/trust'
    | '/upload'
    | '/verification'
    | '/verification-hub'
    | '/viewings'
    | '/welcome'
    | '/profile/$handle'
    | '/properties/$slug'
    | '/spaces/$location'
    | '/properties'
    | '/admin/$section'
    | '/billing/history'
    | '/dashboard/$section'
    | '/dashboard/agent-performance'
    | '/dashboard/favorites'
    | '/dashboard/performance'
    | '/dashboard/properties'
    | '/dashboard/searches'
    | '/property/$id'
    | '/admin'
    | '/dashboard/properties/$id/manage'
    | '/api/public/og/property/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agents'
    | '/auth'
    | '/contact'
    | '/design-system'
    | '/help'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-system'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/business-intelligence'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/leads'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/reviews'
    | '/_authenticated/safety'
    | '/_authenticated/trust'
    | '/_authenticated/upload'
    | '/_authenticated/verification'
    | '/_authenticated/verification-hub'
    | '/_authenticated/viewings'
    | '/_authenticated/welcome'
    | '/profile/$handle'
    | '/properties/$slug'
    | '/spaces/$location'
    | '/properties/'
    | '/_authenticated/admin/$section'
    | '/_authenticated/billing/history'
    | '/_authenticated/dashboard/$section'
    | '/_authenticated/dashboard/agent-performance'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/performance'
    | '/_authenticated/dashboard/properties'
    | '/_authenticated/dashboard/searches'
    | '/_authenticated/property/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/properties/$id/manage'
    | '/api/public/og/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustSystemRoute: typeof TrustSystemRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  SpacesLocationRoute: typeof SpacesLocationRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ApiPublicOgPropertyIdRoute: typeof ApiPublicOgPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-system': {
      id: '/trust-system'
      path: '/trust-system'
      fullPath: '/trust-system'
      preLoaderRoute: typeof TrustSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$location': {
      id: '/spaces/$location'
      path: '/spaces/$location'
      fullPath: '/spaces/$location'
      preLoaderRoute: typeof SpacesLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viewings': {
      id: '/_authenticated/viewings'
      path: '/viewings'
      fullPath: '/viewings'
      preLoaderRoute: typeof AuthenticatedViewingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification-hub': {
      id: '/_authenticated/verification-hub'
      path: '/verification-hub'
      fullPath: '/verification-hub'
      preLoaderRoute: typeof AuthenticatedVerificationHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust': {
      id: '/_authenticated/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AuthenticatedTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety': {
      id: '/_authenticated/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-intelligence': {
      id: '/_authenticated/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/business-intelligence'
      preLoaderRoute: typeof AuthenticatedBusinessIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/property/$id': {
      id: '/_authenticated/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof AuthenticatedPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/searches': {
      id: '/_authenticated/dashboard/searches'
      path: '/searches'
      fullPath: '/dashboard/searches'
      preLoaderRoute: typeof AuthenticatedDashboardSearchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/properties': {
      id: '/_authenticated/dashboard/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/performance': {
      id: '/_authenticated/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof AuthenticatedDashboardPerformanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agent-performance': {
      id: '/_authenticated/dashboard/agent-performance'
      path: '/agent-performance'
      fullPath: '/dashboard/agent-performance'
      preLoaderRoute: typeof AuthenticatedDashboardAgentPerformanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/$section': {
      id: '/_authenticated/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof AuthenticatedDashboardSectionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/billing/history': {
      id: '/_authenticated/billing/history'
      path: '/history'
      fullPath: '/billing/history'
      preLoaderRoute: typeof AuthenticatedBillingHistoryRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/admin/$section': {
      id: '/_authenticated/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AuthenticatedAdminSectionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/og/property/$id': {
      id: '/api/public/og/property/$id'
      path: '/api/public/og/property/$id'
      fullPath: '/api/public/og/property/$id'
      preLoaderRoute: typeof ApiPublicOgPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/properties/$id/manage': {
      id: '/_authenticated/dashboard/properties/$id/manage'
      path: '/$id/manage'
      fullPath: '/dashboard/properties/$id/manage'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesIdManageRouteImport
      parentRoute: typeof AuthenticatedDashboardPropertiesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSectionRoute: typeof AuthenticatedAdminSectionRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSectionRoute: AuthenticatedAdminSectionRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBillingRouteChildren {
  AuthenticatedBillingHistoryRoute: typeof AuthenticatedBillingHistoryRoute
}

const AuthenticatedBillingRouteChildren: AuthenticatedBillingRouteChildren = {
  AuthenticatedBillingHistoryRoute: AuthenticatedBillingHistoryRoute,
}

const AuthenticatedBillingRouteWithChildren =
  AuthenticatedBillingRoute._addFileChildren(AuthenticatedBillingRouteChildren)

interface AuthenticatedDashboardPropertiesRouteChildren {
  AuthenticatedDashboardPropertiesIdManageRoute: typeof AuthenticatedDashboardPropertiesIdManageRoute
}

const AuthenticatedDashboardPropertiesRouteChildren: AuthenticatedDashboardPropertiesRouteChildren =
  {
    AuthenticatedDashboardPropertiesIdManageRoute:
      AuthenticatedDashboardPropertiesIdManageRoute,
  }

const AuthenticatedDashboardPropertiesRouteWithChildren =
  AuthenticatedDashboardPropertiesRoute._addFileChildren(
    AuthenticatedDashboardPropertiesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSectionRoute: typeof AuthenticatedDashboardSectionRoute
  AuthenticatedDashboardAgentPerformanceRoute: typeof AuthenticatedDashboardAgentPerformanceRoute
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardPerformanceRoute: typeof AuthenticatedDashboardPerformanceRoute
  AuthenticatedDashboardPropertiesRoute: typeof AuthenticatedDashboardPropertiesRouteWithChildren
  AuthenticatedDashboardSearchesRoute: typeof AuthenticatedDashboardSearchesRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSectionRoute: AuthenticatedDashboardSectionRoute,
    AuthenticatedDashboardAgentPerformanceRoute:
      AuthenticatedDashboardAgentPerformanceRoute,
    AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
    AuthenticatedDashboardPerformanceRoute:
      AuthenticatedDashboardPerformanceRoute,
    AuthenticatedDashboardPropertiesRoute:
      AuthenticatedDashboardPropertiesRouteWithChildren,
    AuthenticatedDashboardSearchesRoute: AuthenticatedDashboardSearchesRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRouteWithChildren
  AuthenticatedBusinessIntelligenceRoute: typeof AuthenticatedBusinessIntelligenceRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSafetyRoute: typeof AuthenticatedSafetyRoute
  AuthenticatedTrustRoute: typeof AuthenticatedTrustRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedVerificationHubRoute: typeof AuthenticatedVerificationHubRoute
  AuthenticatedViewingsRoute: typeof AuthenticatedViewingsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedPropertyIdRoute: typeof AuthenticatedPropertyIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRouteWithChildren,
  AuthenticatedBusinessIntelligenceRoute:
    AuthenticatedBusinessIntelligenceRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSafetyRoute: AuthenticatedSafetyRoute,
  AuthenticatedTrustRoute: AuthenticatedTrustRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedVerificationHubRoute: AuthenticatedVerificationHubRoute,
  AuthenticatedViewingsRoute: AuthenticatedViewingsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedPropertyIdRoute: AuthenticatedPropertyIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustSystemRoute: TrustSystemRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  SpacesLocationRoute: SpacesLocationRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ApiPublicOgPropertyIdRoute: ApiPublicOgPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
